### ISSUE TITLE
The content here may need to be corrected

### ISSUE THREAD

**Issue by 321HG** [justinlovinger/optimal-py#1]
File "F:.........\optimal\algorithms\genalg.py", line 32, in <module>
    from optimal import gaoperators, optimize, common

  File "F:..........\optimal\optimize.py", line 57
    print 'Iteration: %s\nAvg Fitness: %s\nBest Fitness: %s' % (
                                                           ^
SyntaxError: invalid syntax

**Comment by JustinLovinger** [comment]
Are you using Python 2?

**Comment by HQYGzxc** [comment]
It has been solved, thank you.

**Comment by sugurova** [comment]
TypeError: 'map' object is not subscriptable in optimize.py
